services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agropet-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=UmaSenhaForte#123
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

  api:
    build: .
    container_name: agropet-api
    depends_on:
      - db
    ports:
      - "80:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=Agropet;User Id=sa;Password=UmaSenhaForte#123;TrustServerCertificate=True;
      - Agropet-JWT-Key=589830928foleab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b37274dfhsfkjhb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a6sdiufy89
      - Agropet-JWT-Issuer=MinhaApi.Auth
      - Agropet-JWT-Audience=MinhaApi
    restart: always

volumes:
  mssql_data:
